feature:
  - '(feat|feature).*'
bugfix:
  - '(fix|bugfix).*'
documentation:
  - '(docs|documentation).*'
chore:
  - '(chore|maintenance).*'
refactor:
  - '(refactor|improvement).*'
testing:
  - '(test|testing).*'